pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
rootProject.name="awesomeAndroidApp"
plugins {
    id("com.gradle.develocity") version "4.0.2"
    id("com.gradle.common-custom-user-data-gradle-plugin") version "2.2"

}

develocity {
    server = "https://ge.solutions-team.gradle.com/"
    allowUntrustedServer = true
    buildScan {
        uploadInBackground.set(false)
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
include (":core:push")
include (":core:contact")
include (":core:login")
include (":core:identity")
include (":core:checkout")
include (":core:cart")
include (":core:user")
include (":core:profile")
include (":core:feed")
include (":core:comment")
include (":core:post")
include (":core:search")
include (":core:location")
include (":core:network")
include (":core:sync")
include (":core:share")
include (":core:group")
include (":core:message")
include (":core:notification")
include (":core:setting")
include (":core:account")
include (":core:session")
include (":core:analytics")
include (":core:report")
include (":core:log")
include (":core:status")
include (":core:metric")
include (":core:task")
include (":core:calendar")
include (":core:event")
include (":core:alarm")
include (":core:timer")
include (":core:file")
include (":feature:document")
include (":feature:note")
include (":feature:todo")
include (":feature:list")
include (":feature:map")
include (":feature:weather")
include (":feature:forecast")
include (":feature:news")
include (":feature:article")
include (":feature:podcast")
include (":feature:video")
include (":feature:photo")
include (":feature:gallery")
include (":feature:media")
include (":feature:audio")
include (":feature:playlist")
include (":feature:push-contact")
include (":feature:contact-contact")
include (":feature:login-contact")
include (":feature:identity-contact")
include (":feature:checkout-contact")
include (":feature:cart-contact")
include (":feature:user-contact")
include (":feature:profile-contact")
include (":feature:feed-contact")
include (":feature:comment-contact")
include (":feature:post-contact")
include (":feature:search-contact")
include (":feature:location-contact")
include (":feature:network-contact")
include (":feature:sync-contact")
include (":feature:share-contact")
include (":feature:group-contact")
include (":feature:message-contact")
include (":feature:notification-contact")
include (":feature:setting-contact")
include (":feature:account-contact")
include (":feature:session-contact")
include (":feature:analytics-contact")
include (":feature:report-contact")
include (":feature:log-contact")
include (":feature:status-contact")
include (":feature:metric-contact")
include (":feature:task-contact")
include (":feature:calendar-contact")
include (":feature:event-contact")
include (":feature:alarm-contact")
include (":feature:timer-contact")
include (":feature:file-contact")
include (":feature:document-contact")
include (":feature:note-contact")
include (":feature:todo-contact")
include (":feature:list-contact")
include (":feature:map-contact")
include (":feature:weather-contact")
include (":feature:forecast-contact")
include (":feature:news-contact")
include (":feature:article-contact")
include (":feature:podcast-contact")
include (":feature:video-contact")
include (":feature:photo-contact")
include (":feature:gallery-contact")
include (":feature:media-contact")
include (":feature:audio-contact")
include (":feature:playlist-contact")
include (":feature:push-login")
include (":domain:contact-login")
include (":repository:login-login")
include (":repository:identity-login")
include (":repository:checkout-login")
include (":repository:cart-login")
include (":repository:user-login")
include (":repository:profile-login")
include (":repository:feed-login")
include (":repository:comment-login")
include (":repository:post-login")
include (":repository:search-login")
include (":repository:location-login")
include (":repository:network-login")
include (":repository:sync-login")
include (":repository:share-login")
include (":repository:group-login")
include (":repository:message-login")
include (":repository:notification-login")
include (":repository:setting-login")
include (":repository:account-login")
include (":repository:session-login")
include (":repository:analytics-login")
include (":repository:report-login")
include (":repository:log-login")
include (":repository:status-login")
include (":repository:metric-login")
include (":repository:task-login")
include (":repository:calendar-login")
include (":repository:event-login")
include (":repository:alarm-login")
include (":repository:timer-login")
include (":repository:file-login")
include (":repository:document-login")
include (":repository:note-login")
include (":repository:todo-login")
include (":repository:list-login")
include (":repository:map-login")
include (":repository:weather-login")
include (":repository:forecast-login")
include (":repository:news-login")
include (":repository:article-login")
include (":repository:podcast-login")
include (":repository:video-login")
include (":repository:photo-login")
include (":repository:gallery-login")
include (":repository:media-login")
include (":repository:audio-login")
include (":repository:playlist-login")
include (":repository:push-identity")
include (":repository:contact-identity")
include (":repository:login-identity")
include (":repository:identity-identity")
include (":repository:checkout-identity")
include (":repository:cart-identity")
include (":repository:user-identity")
include (":model:profile-identity")
include (":model:feed-identity")
include (":model:comment-identity")
include (":model:post-identity")
include (":model:search-identity")
include (":model:location-identity")
include (":model:network-identity")
include (":model:sync-identity")
include (":model:share-identity")
include (":model:group-identity")
include (":model:message-identity")
include (":model:notification-identity")
include (":model:setting-identity")
include (":model:account-identity")
include (":model:session-identity")
include (":model:analytics-identity")
include (":model:report-identity")
include (":model:log-identity")
include (":model:status-identity")
include (":model:metric-identity")
include (":model:task-identity")
include (":model:calendar-identity")
include (":model:event-identity")
include (":model:alarm-identity")
include (":model:timer-identity")
include (":model:file-identity")
include (":model:document-identity")
include (":app:app")
